CREATE DATABASE gc200528741;
USE gc200528741;

CREATE TABLE products (
	id int NOT NULL AUTO_INCREMENT,
    product_name VARCHAR(50),
    price INT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);